# Generated by Django 3.0.3 on 2020-04-30 14:24

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacto', models.IntegerField()),
                ('detalle', ckeditor.fields.RichTextField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria_donacion', to='donaciones.Categoria')),
                ('usuario_donador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_donador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'donacion',
                'verbose_name_plural': 'donaciones',
            },
        ),
    ]
