# Generated by Django 3.0.3 on 2020-05-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donacion',
            name='contacto',
            field=models.BigIntegerField(),
        ),
    ]
