# Generated by Django 3.0.3 on 2020-05-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0002_auto_20200502_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donacion',
            name='contacto',
            field=models.CharField(max_length=25),
        ),
    ]
